`rm Podfile.lock`

platform :ios, '8.0'
use_frameworks!

target 'MCJSONKit_Example' do
  pod 'MCJSONKit', :path => '../'
  pod 'MJExtension'
  pod 'MCUIKit'
  pod 'MCLogger'

  target 'MCJSONKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'

  end
end
