name: CI

on: [push]
  branchs:
  - master

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        pod install --project-directory=Example
        xcodebuild clean test -enableCodeCoverage=YES -workspace Example/MCJSONKit.xcworkspace -scheme 'MCJSONKit-Example' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6s,OS=latest' -configuration Debug | xcpretty -c

